CREATE TABLE `wc2110mvars` (
  `coordCode` INT NOT NULL,
  `tmin` INT NULL,
  `tavg` INT NULL,
  `tmax` INT NULL,
  `prec` INT NULL,
  `vapr` INT NULL,
  `wind` INT NULL,
  `srad` INT NULL,
  `bio1` INT NULL COMMENT 'Annual mean temperature',
  `bio2` INT NULL COMMENT 'Mean diurnal temperature range',
  `bio3` INT NULL COMMENT 'Isothermality',
  `bio4` INT NULL COMMENT 'Temperature seasonality',
  `bio5` INT NULL COMMENT 'Maximum temperature of warmest month',
  `bio6` INT NULL COMMENT 'Minimum temperature of coldest month',
  `bio7` INT NULL COMMENT 'Annual temperature range',
  `bio8` INT NULL COMMENT 'Mean temperature of wettest quarter',
  `bio9` INT NULL COMMENT 'Mean temperature of driest quarter',
  `bio10` INT NULL COMMENT 'Mean temperature of warmest quarter',
  `bio11` INT NULL COMMENT 'Mean temperature of coldest quarter',
  `bio12` INT NULL COMMENT 'Annual precipitation',
  `bio13` INT NULL COMMENT 'Precipitation of westtest month',
  `bio14` INT NULL COMMENT 'Precipitation of driest month',
  `bio15` INT NULL COMMENT 'Precipitation seasonality',
  `bio16` INT NULL COMMENT 'Precipitation of wettest quarter',
  `bio17` INT NULL COMMENT 'Precipitation of driest quarter',
  `bio18` INT NULL COMMENT 'Precipitation of warmest quarter',
  `bio19` INT NULL COMMENT 'Precipitation of coldest quarter',
  `initialTimestamp` TIMESTAMP NULL DEFAULT current_timestamp,
  PRIMARY KEY (`coordCode`)
  )  ENGINE = MyISAM;